### ISSUE TITLE
Error running web GUI

### ISSUE THREAD

**Issue by SurferZergy** [montvieux/plark_ai_public#1]
Hi,

running docker container straight from git clone got me this error at http://localhost:5000/

jinja2.exceptions.TemplateNotFound
jinja2.exceptions.TemplateNotFound: index.html

Traceback (most recent call last)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
Open an interactive python shell in this framerv = self.dispatch_request()
File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Components/plark_ai_flask/plark_ai_flask.py", line 65, in home
return render_template('index.html')
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 138, in render_template
ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
return self._load_template(name, self.make_globals(globals))
File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
template = self.loader.load(self, name, globals)
File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 113, in load
source, filename, uptodate = self.get_source(environment, name)
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 60, in get_source
return self._get_source_fast(environment, template)
File "/usr/local/lib/python3.6/dist-packages/flask/templating.py", line 89, in _get_source_fast
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by aidan-mv** [comment]
Hi,

Please build the angular by running this command "sh build_angular.sh"  
I was able to reproduce the error by cloning a fresh version of the repository and starting the docker before running the angular build script. 
I was then able to resolve the issue by shutting down the docker instance, running "sh build_angular.sh", then starting the docker instance.
Please ensure you follow these steps below. 
> git clone https://github.com/montvieux/plark_ai_public.git
> cd plark_ai_public
> sh build_angular.sh
> pwd 
/Users/aidanjones/repos/plark_ai_public
> docker build -t plark_ai -f /Users/aidanjones/repos/plark_ai_public/Docker/DockerfileCPU  /Users/aidanjones/repos/plark_ai_public/Docker
> docker run -v /Users/aidanjones/repos/plark_ai_public/Components:/Components -v /Users/aidanjones/repos/plark_ai_public/data:/data -p 8888:8888 -p 5000:5000 plark_ai
http://localhost:5000
